### ISSUE TITLE
JetPack "desired" Request not correctly understood by the CoolBoard

### ISSUE THREAD

**Issue by 3rwww1** [LeClubSandwichStudio/LaCOOLBoard#1]
Sending MQTT request to "desired" topic
```
{"state":{"desired":{ "jetPatck": { "Act3": {"high":[23,200000,6,0]}}}}}
```

CoolBoard received the desired message and reboot BUT "high" element are not correctly interpreted. JetPack config is not updated.

**Comment by 3rwww1** [comment]
originally submitted by @RomainTourte

**Comment by LeSuedois** [comment]
the command is working fine, IMO the coolboard does all right with not accepting a command for a non existing "jetPa**t**ck". 
This command was tested and is working:
`{"state":{"desired":{ "jetPack": { "Act3": {"high":[23,200000,6,0]}}}}}`
