### ISSUE TITLE
MQTT timeout is very, very long and needs to be reduced to 5s at most

### ISSUE THREAD

**Issue by 3rwww1** [LeClubSandwichStudio/LaCOOLBoard#109]
**estimate:** 1d

This is probably related to MQTTS or 2.5.0

We need to test with later versions of the SDK

**Steps to reproduce**
* simulate bad wifi connection (get far or une bad network
* wait for MQTT connetion to be established
* Interrupt Wifi when message to start sending
* **Hard to reproduce, try 10-20 times at least**

**Expected behavior**
* message sending fails, and log is saved on SPIFFS as JSON :heavy_check_mark: 

**Actual behavior**
* or after a very very long time (TBD) :question: 
* the code never returns from the publish function :x:
* or when Wifi connection is back online :x:

**Comment by Kameeno** [comment]
i tested with my branch about ntp/rtc enhancement and the last master, it's working good if there's wifi connection but no internet.
i remarked also another strange thing, if wifi is disconnected and i arrive to reconnect, my coolboard do a reboot,
