### ISSUE TITLE
Irene3000 does not save configuration

### ISSUE THREAD

**Issue by LeSuedois** [LeClubSandwichStudio/LaCOOLBoard#135]
**estimate:** 1d

before we had the following usage for calibrating our Ph/Temp interface : 

1.  push the button on irene when the Led get's white
2.  the light get's green, put it in the green liquid, push the button 2 seconds
3.  led goes bright green for 30sec, then the ph7 calibration is finished
4.  the led get's red, put it in the red liquid, push the button for 2 seconds
5. led goes bright red for 30 sec then the ph4 is ok
6. the led goes violet and waits for a last push on the button, then the ph calibration is finished 

when I tested the calibration today it went like this:
step 1-4 acted the same
5. the light goes violet for 30 seconds
6. the light get's white, waits for a push on the button 
**but the main problem is that the calibration is not made or saved and the Ph is still around 130..**

**Comment by Kameeno** [comment]
assigned to @simon-lacool  by @3rwww1  request
