### ISSUE TITLE
Reliable way to make SHT1x work, with jetpack

### ISSUE THREAD

**Issue by 3rwww1** [LeClubSandwichStudio/LaCOOLBoard#141]
**estimate:** 2d

**Steps to reproduce**
* use COOL cave
* Ensure IRN3000, onboard sensors, CO², Jetpack are plugged-in and configured
* Add SDS11, SHT1x, I²C hub

**Expected behavior**
* SDS11 works (that checks I²C hub)
* IRN3000 works
* SHT1x works
* CO² works
* Jetpack works
* RTC works
* onboard sensors work
* all of the above with `sleepMode` true and false

**Actual behavior**
* Jetpack doesn't work :question: 
* SDS11 and all I²C sensors don't work :x:
* IRN 3000 doesn't work :x:
* CO² doesn't work :x:
* onboard sensors don't work :x:
* RTC sensors don't work :x:

**Comment by Kameeno** [comment]
we got another sht? so normally can work, we have changed the pin to use. 
if i found one i go to test it

**Comment by LeSuedois** [comment]
pins where changes in commit https://github.com/LaCoolCo/LaCOOLBoard/commit/9f11a2a1ea9b84aea8802ff6e58be2fff29f1025 . 
one SDS011 and one SHT01 are on my table!

**Comment by LeSuedois** [comment]
Pin assignment on 0 & 12 is not working with the jetpack. Please deprecate this way to get this sensor if you use the Jetpack!
**It blocks the CoolBoard like if you put it in load position.**

Using this sensor without jetpack seems to work nice.

**Comment by LeSuedois** [comment]
after 3 days without problem I confirm that pin 0 and 12 work fine for the SHT1x on the CoolCave with all other sensors: CO2, SDS011, onboard sensors...
I close this issue, but anyway I will have an eye on it...
