### ISSUE TITLE
Ensure jetpack accepts rules based on a recorded metric

### ISSUE THREAD

**Issue by 3rwww1** [LeClubSandwichStudio/LaCOOLBoard#146]
**estimate:** 2d

**What to do**

* turn on/off a thermostat when temperature meets certain thresholds (too hot or too cold)
* test with  `sleepMode: true`
* test bed with La COOL Cave : 
* turn off light when CO² level is too high (breathe in sensor admission)
* two LEDs : turn on if light too low, turn if light too bright (lights out and cellphone flash resp.)

**Comment by Kameeno** [comment]
any indication about how to rule actions by beasures ? there's something on the coolapi about ?

**Comment by Kameeno** [comment]
working, 
not possible to configure via OTA, need to flash the spiffs

**Comment by LeSuedois** [comment]
I tested most functions too, all is working. I think soon we should look for a rules engine to be more flexible..
