### ISSUE TITLE
Has Stopped Flag from RTC not used!

### ISSUE THREAD

**Issue by LeSuedois** [LeClubSandwichStudio/LaCOOLBoard#24]
**estimate: 0.5d**

**Steps to reproduce**
* Use a board with no battery, no coin cell
* Make it run 1 time, normally, so that it synchronizes with NTP
* Disconnect the wifi (or Internet) so that it can't sync again with NTP
* Cut the power to the board, and replug it in

**Expected behavior**
* COOL Board refuses to record anything because it has detected the RTC was stopped :heavy_check_mark: 
* Putting the network back online makes it send logs again :heavy_check_mark: 

**Actual behavior**
* The logs are saved as JSON, **but the timestamp is incorrect** (year 2066, 1999, 1970, 2000...) :x:

**Background**
When we have no coin cell _and_ the board looses power, a stopped flag (OSF) is set on the RTC IC.

However, the OSF flag is never read. Actually, the current DS1337 RTC lib we use doesn't provide a function to read it at all.

This is critical because it leads to devices reporting dates in 2000 or 2066. **And we have now way of knowing those records are wrong.** From the outside, everything looks fine, except we cannot plot any data.

The solution is a **two step process** that requires **two separate pull requests**
- change the current DS1337 lib for https://github.com/cyberp/DS1337 which exposes the OSF flag
- for now, do not send or store anything if we can't get an NTP sync and the OSF flag is set to 1.

**Comment by 3rwww1** [comment]
- Investigate other libraries (@simon-lacool finds the old one)
- Try patching the current library
