### ISSUE TITLE
Add a timeout if you missed to turn off the manual mode

### ISSUE THREAD

**Issue by Kameeno** [LeClubSandwichStudio/LaCOOLBoard#40]
i propose a timeout to auto-turnOFF the manual mode, it's better to drive this inside the coolboard FW or via Backend?

**Comment by 3rwww1** [comment]
There should be an alert on the backend. But we can also implement some kind of failsafe firmare side.

**Comment by 3rwww1** [comment]
not a good idea to do that on the board. We'd better send an alert from the cloud.
