### ISSUE TITLE
Upgrade to SDK 2.4.1

### ISSUE THREAD

**Issue by 3rwww1** [LeClubSandwichStudio/LaCOOLBoard#41]

**Comment by trap98** [comment]
Problem at the compilation with SDK 2.4.1 on the library DS1337RTC.

**Comment by Kameeno** [comment]
on the new porting on the last SDK, cause bug about connectivity, so, if on your spiffs you got some saved SSID/PASSWORD on wificonfig.json the board, i think she did not take the credential and arent compared with the current wifi arround.

ok, if you flash your firmware and on your spiffs, wificonfig.json did not contain some wifi credentials, you arrive to connect, i do my OTA update, (with the same firmware) on reboot she didn't getting credentials from wificonfig.json

actually i missed my coolboard to make a good bugfix about
