### ISSUE TITLE
Irene3000 and external sensors are not working anymore

### ISSUE THREAD

**Issue by LeSuedois** [LeClubSandwichStudio/LaCOOLBoard#67]
**estimate:** 2j

when I reinstalled the CoolCave I noticed that Irene and the external sensors are no more working. the configurations are allright but the metrics are not sent.
Maybe it's because of and old (1-2 weeks) software version but not shure.
This needs to be investigated asap!

**Comment by LeSuedois** [comment]
ok, I restarted the board and Irene is working now...
but still no externalSensors...

**Comment by Kameeno** [comment]
Tomorrow I hope the new mqtts going to be validate and we merge this with OTAupdates and I go to investigate about.
