### ISSUE TITLE
LED doesn't blink if adding Wifi network fails

### ISSUE THREAD

**Issue by 3rwww1** [LeClubSandwichStudio/LaCOOLBoard#80]
**Steps to reproduce**
1. Flash the board from scratch
2. Setup a temporary Wifi hotspot (e.g with your phone)
2. Boot the board in AP mode and select your temporary Wifi hotspot in the web interface
3. **Immediatly turn off the AP so that the COOL Board cannot connect**
4. Observe the error in the logs and the COOL Board LED

**Expected behavior**
- The LED should turn from purple to red, indicating a network issue

**Actual behavior**
- LED does not blink red and the user can't know the Wifi configuration failed.

**Comment by Axe-R** [comment]
It works but it takes 2min30 for the COOLBoard's LED to turn red.
