### ISSUE TITLE
SHT01 temperature and soil humidity sensor

### ISSUE THREAD

**Issue by 3rwww1** [LeClubSandwichStudio/LaCOOLBoard#87]
**estimate:** 1d

STH01 reports:
- Soil temperature in °C
- Soil humidity in %
- ~Soil temperature in °F~ (unused in our case)

STH01 is supposed to work on the I²C bus, but simply doesn't.
@Kameeno tried to plug it to the JetPack pin, which seems to work, but it's not reasonable for compatibily issues.

We need to:
- retest it on I²C bus and make sure it does not interfere with other I²C devices
- integrate it external sensors
- report the values

**Comment by Kameeno** [comment]
is not possible to make it works on i2c pins, he cause wrong read values of i2c sensors, the functions like ```wire.end();``` are only reserved for AVR mcu's, so for the moment is running on pin's 12 and 13 with a pullup on 12 (data pin) & a pulldown for pin 13 (clock pin),

these pins are on the board for the analog switch(12) and (13) to enable the onboard Moisture sensor. 

putting this sensor to i2c pins caused to me strange stuff like, mqtts disconnection (without possibility to reconnect, NTP server unresponsive after running it for 15/20 minutes) .

**Comment by 3rwww1** [comment]
@Kameeno, regarding your latest comment, have you seen with @simon-lacool what would be the most cost-effective solution ? Use the soil moisture fork pins and not our I²C pins ?
