### ISSUE TITLE
COOL Board AP's are randomly visible, but HTTP servers are not accessible

### ISSUE THREAD

**Issue by 3rwww1** [LeClubSandwichStudio/LaCOOLBoard#95]
**estimate:** 1d

Coolboard are starting their Wifi access point even if we didn't asked them to

**Steps to reproduce**
* COOL Board with `sleepActive: true*
* Start Wifi access point (LOAD or no wifi configured)
* Finish AP configuration

**Expected**
* AP is off :heavy_check_mark:

**Actual**
* AP is ON :x:

**Background**

@trap98 possibly related to #94 ?

I've noticed that a lot of COOL Boards around me (eg. COOL Cave) are visible on my laptops Wifi radar, even though those boards are supposed to be logging normally :
- switch in `RUN` position
- firmware is flashed and board was reset
- board configured with a known hotspot that's supposed to be working

In those cases:
- the LED is off
- I can connect to the COOL Boards AP
- I can't access the boards HTTP server (connection refused)

Hypothesis:
- the board's AP was not cleanly closed/destroyed/stopped after 
- the 2.5.0 beta firmware we are using has a big "ghost access point issue ?"
- we are opening this AP somewhere in our code

**Comment by trap98** [comment]
It's ok for me
